const America = {
  AI: 'Anguilla',
  AR: 'Argentina',
  AW: 'Aruba',
  BS: 'Bahamas',
  BB: 'Barbados',
  BZ: 'Belize',
  BM: 'Bermuda',
  BO: 'Bolivia',
  BR: 'Brazil',
  VG: 'British Virgin Islands',
  CA: 'Canada',
  KY: 'Cayman Islands',
  CL: 'Chile',
  CO: 'Colombia',
  CR: 'Costa Rica',
  CU: 'Cuba',
  CW: 'Curacao',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  EC: 'Ecuador',
  SV: 'El Salvador',
  FK: 'Falkland Islands',
  GL: 'Greenland',
  GP: 'Guadeloupe',
  GT: 'Guatemala',
  GY: 'Guyana',
  HT: 'Haiti',
  HN: 'Honduras',
  JM: 'Jamaica',
  MX: 'Mexico',
  MS: 'Montserrat',
  NI: 'Nicaragua',
  PA: 'Panama',
  PY: 'Paraguay',
  PE: 'Peru',
  PR: 'Puerto Rico',
  BL: 'Saint Barthélemy',
  KN: 'Saint Kitts and Nevis',
  LC: 'Saint Lucia',
  MF: 'Saint Martin',
  PM: 'Saint Pierre and Miquelon',
  VC: 'Saint Vincent and the Grenadines',
  SR: 'Suriname',
  TT: 'Trinidad and Tobago',
  US: 'United States',
  UY: 'Uruguay',
  VE: 'Venezuela',
};

export default America;
